// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package ore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaySongRequest struct {
	SongToPlay           Song     `protobuf:"varint,1,opt,name=song_to_play,json=songToPlay,proto3,enum=ore.Song" json:"song_to_play,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaySongRequest) Reset()         { *m = PlaySongRequest{} }
func (m *PlaySongRequest) String() string { return proto.CompactTextString(m) }
func (*PlaySongRequest) ProtoMessage()    {}
func (*PlaySongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PlaySongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaySongRequest.Unmarshal(m, b)
}
func (m *PlaySongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaySongRequest.Marshal(b, m, deterministic)
}
func (m *PlaySongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaySongRequest.Merge(m, src)
}
func (m *PlaySongRequest) XXX_Size() int {
	return xxx_messageInfo_PlaySongRequest.Size(m)
}
func (m *PlaySongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaySongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaySongRequest proto.InternalMessageInfo

func (m *PlaySongRequest) GetSongToPlay() Song {
	if m != nil {
		return m.SongToPlay
	}
	return Song_SONG_UNKNOWN
}

type PlaySongResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaySongResponse) Reset()         { *m = PlaySongResponse{} }
func (m *PlaySongResponse) String() string { return proto.CompactTextString(m) }
func (*PlaySongResponse) ProtoMessage()    {}
func (*PlaySongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *PlaySongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaySongResponse.Unmarshal(m, b)
}
func (m *PlaySongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaySongResponse.Marshal(b, m, deterministic)
}
func (m *PlaySongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaySongResponse.Merge(m, src)
}
func (m *PlaySongResponse) XXX_Size() int {
	return xxx_messageInfo_PlaySongResponse.Size(m)
}
func (m *PlaySongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaySongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaySongResponse proto.InternalMessageInfo

type PauseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseRequest) Reset()         { *m = PauseRequest{} }
func (m *PauseRequest) String() string { return proto.CompactTextString(m) }
func (*PauseRequest) ProtoMessage()    {}
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *PauseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRequest.Unmarshal(m, b)
}
func (m *PauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRequest.Marshal(b, m, deterministic)
}
func (m *PauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRequest.Merge(m, src)
}
func (m *PauseRequest) XXX_Size() int {
	return xxx_messageInfo_PauseRequest.Size(m)
}
func (m *PauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRequest proto.InternalMessageInfo

type PauseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseResponse) Reset()         { *m = PauseResponse{} }
func (m *PauseResponse) String() string { return proto.CompactTextString(m) }
func (*PauseResponse) ProtoMessage()    {}
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *PauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseResponse.Unmarshal(m, b)
}
func (m *PauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseResponse.Marshal(b, m, deterministic)
}
func (m *PauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseResponse.Merge(m, src)
}
func (m *PauseResponse) XXX_Size() int {
	return xxx_messageInfo_PauseResponse.Size(m)
}
func (m *PauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PauseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlaySongRequest)(nil), "ore.PlaySongRequest")
	proto.RegisterType((*PlaySongResponse)(nil), "ore.PlaySongResponse")
	proto.RegisterType((*PauseRequest)(nil), "ore.PauseRequest")
	proto.RegisterType((*PauseResponse)(nil), "ore.PauseResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x2d, 0xa2, 0xe8, 0xd0, 0x0f, 0x1d, 0x14, 0x4a, 0x4e, 0x12, 0x44, 0x04, 0xe9, 0xae,
	0x44, 0x10, 0xbc, 0x78, 0xf0, 0x05, 0x2c, 0xd6, 0x93, 0x97, 0x92, 0x94, 0x31, 0x06, 0xeb, 0x4e,
	0x9c, 0xdd, 0x15, 0xf2, 0xf6, 0x92, 0xdd, 0x94, 0x86, 0xdc, 0x76, 0x66, 0x7e, 0xff, 0x0f, 0x16,
	0x26, 0x96, 0xe4, 0xaf, 0xda, 0x90, 0xaa, 0x85, 0x1d, 0xe3, 0x21, 0x0b, 0x25, 0xf3, 0xf0, 0x2e,
	0xfc, 0xa7, 0x66, 0x21, 0x6d, 0xd9, 0x94, 0x36, 0x9e, 0xd3, 0x67, 0x98, 0x2d, 0xb7, 0x79, 0xb3,
	0x62, 0x53, 0xbe, 0xd1, 0xaf, 0x27, 0xeb, 0xf0, 0x0e, 0xc6, 0x2d, 0xb1, 0x76, 0xbc, 0xae, 0xb7,
	0x79, 0x33, 0x1f, 0x5d, 0x8d, 0x6e, 0xa7, 0xd9, 0xa9, 0x62, 0x21, 0x15, 0x38, 0x68, 0xcf, 0xef,
	0xdc, 0xea, 0x52, 0x84, 0xb3, 0xbd, 0xde, 0xd6, 0x6c, 0x2c, 0xa5, 0x53, 0x18, 0x2f, 0x73, 0x6f,
	0xa9, 0x33, 0x4c, 0x67, 0x30, 0xe9, 0xe6, 0x08, 0x64, 0x0d, 0xc0, 0xab, 0xd0, 0x2a, 0xf6, 0xc4,
	0x27, 0x38, 0xd9, 0x59, 0xe0, 0x45, 0x48, 0x19, 0x34, 0x4a, 0x2e, 0x07, 0xdb, 0x2e, 0xe7, 0x00,
	0xef, 0xe1, 0x28, 0x38, 0xe3, 0x79, 0x24, 0x7a, 0xa9, 0x09, 0xf6, 0x57, 0x3b, 0xc5, 0xcb, 0xcd,
	0xc7, 0x75, 0x59, 0xb9, 0x2f, 0x5f, 0xa8, 0x0d, 0xff, 0xe8, 0x4a, 0xd8, 0x2c, 0x58, 0x68, 0x91,
	0x3d, 0x7e, 0xeb, 0xfe, 0x1f, 0x15, 0xc7, 0x61, 0x7a, 0xf8, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x08,
	0xfa, 0x12, 0xcb, 0x4e, 0x01, 0x00, 0x00,
}
