// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: songs.proto

package ore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Song int32

const (
	Song_SONG_UNKNOWN                    Song = 0
	Song_SONG_WRECK_OF_EDMUND_FITZGERALD Song = 1
	Song_SONG_FORTUNATE_SON              Song = 2
)

// Enum value maps for Song.
var (
	Song_name = map[int32]string{
		0: "SONG_UNKNOWN",
		1: "SONG_WRECK_OF_EDMUND_FITZGERALD",
		2: "SONG_FORTUNATE_SON",
	}
	Song_value = map[string]int32{
		"SONG_UNKNOWN":                    0,
		"SONG_WRECK_OF_EDMUND_FITZGERALD": 1,
		"SONG_FORTUNATE_SON":              2,
	}
)

func (x Song) Enum() *Song {
	p := new(Song)
	*p = x
	return p
}

func (x Song) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Song) Descriptor() protoreflect.EnumDescriptor {
	return file_songs_proto_enumTypes[0].Descriptor()
}

func (Song) Type() protoreflect.EnumType {
	return &file_songs_proto_enumTypes[0]
}

func (x Song) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Song.Descriptor instead.
func (Song) EnumDescriptor() ([]byte, []int) {
	return file_songs_proto_rawDescGZIP(), []int{0}
}

var File_songs_proto protoreflect.FileDescriptor

var file_songs_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f,
	0x72, 0x65, 0x2a, 0x55, 0x0a, 0x04, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4f,
	0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f,
	0x53, 0x4f, 0x4e, 0x47, 0x5f, 0x57, 0x52, 0x45, 0x43, 0x4b, 0x5f, 0x4f, 0x46, 0x5f, 0x45, 0x44,
	0x4d, 0x55, 0x4e, 0x44, 0x5f, 0x46, 0x49, 0x54, 0x5a, 0x47, 0x45, 0x52, 0x41, 0x4c, 0x44, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x4e, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x54, 0x55, 0x4e,
	0x41, 0x54, 0x45, 0x5f, 0x53, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x72, 0x6f, 0x6e, 0x2d, 0x6f, 0x72, 0x65,
	0x2d, 0x32, 0x36, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x72,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_songs_proto_rawDescOnce sync.Once
	file_songs_proto_rawDescData = file_songs_proto_rawDesc
)

func file_songs_proto_rawDescGZIP() []byte {
	file_songs_proto_rawDescOnce.Do(func() {
		file_songs_proto_rawDescData = protoimpl.X.CompressGZIP(file_songs_proto_rawDescData)
	})
	return file_songs_proto_rawDescData
}

var file_songs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_songs_proto_goTypes = []interface{}{
	(Song)(0), // 0: ore.Song
}
var file_songs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_songs_proto_init() }
func file_songs_proto_init() {
	if File_songs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_songs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_songs_proto_goTypes,
		DependencyIndexes: file_songs_proto_depIdxs,
		EnumInfos:         file_songs_proto_enumTypes,
	}.Build()
	File_songs_proto = out.File
	file_songs_proto_rawDesc = nil
	file_songs_proto_goTypes = nil
	file_songs_proto_depIdxs = nil
}
